// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';
import path from 'path';

// Adjust the path to find your root .env if necessary
dotenv.config({
  path: path.resolve(__dirname, '../../.env')
})
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
