module.exports = [
  { name: 'Apple', calories: 52, protein: 0.3, fat: 0.2, fiber: 2.4, hasGluten: false, isVegetarian: true },
  { name: 'Banana', calories: 89, protein: 1.1, fat: 0.3, fiber: 2.6, hasGluten: false, isVegetarian: true },
  { name: 'Orange', calories: 47, protein: 0.9, fat: 0.1, fiber: 2.4, hasGluten: false, isVegetarian: true },
  { name: 'Strawberry', calories: 32, protein: 0.7, fat: 0.3, fiber: 2, hasGluten: false, isVegetarian: true },
  { name: 'Blueberry', calories: 57, protein: 0.7, fat: 0.3, fiber: 2.4, hasGluten: false, isVegetarian: true },
  { name: 'Mango', calories: 60, protein: 0.8, fat: 0.4, fiber: 1.6, hasGluten: false, isVegetarian: true },
  { name: 'Pineapple', calories: 50, protein: 0.5, fat: 0.1, fiber: 1.4, hasGluten: false, isVegetarian: true },
  { name: 'Watermelon', calories: 30, protein: 0.6, fat: 0.2, fiber: 0.4, hasGluten: false, isVegetarian: true },
  { name: 'Avocado', calories: 160, protein: 2, fat: 14.7, fiber: 6.7, hasGluten: false, isVegetarian: true },
  { name: 'Lemon', calories: 29, protein: 1.1, fat: 0.3, fiber: 2.8, hasGluten: false, isVegetarian: true },
  { name: 'Tomato', calories: 18, protein: 0.9, fat: 0.2, fiber: 1.2, hasGluten: false, isVegetarian: true },
  { name: 'Cucumber', calories: 15, protein: 0.7, fat: 0.1, fiber: 0.5, hasGluten: false, isVegetarian: true },
  { name: 'Carrot', calories: 41, protein: 0.9, fat: 0.2, fiber: 2.8, hasGluten: false, isVegetarian: true },
  { name: 'Broccoli', calories: 34, protein: 2.8, fat: 0.4, fiber: 2.6, hasGluten: false, isVegetarian: true },
  { name: 'Cauliflower', calories: 25, protein: 1.9, fat: 0.3, fiber: 2, hasGluten: false, isVegetarian: true },
  { name: 'Spinach', calories: 23, protein: 2.9, fat: 0.4, fiber: 2.2, hasGluten: false, isVegetarian: true },
  { name: 'Kale', calories: 49, protein: 4.3, fat: 0.9, fiber: 3.6, hasGluten: false, isVegetarian: true },
  { name: 'Romaine Lettuce', calories: 17, protein: 1.2, fat: 0.3, fiber: 2.1, hasGluten: false, isVegetarian: true },
  { name: 'Red Bell Pepper', calories: 31, protein: 1, fat: 0.3, fiber: 2.1, hasGluten: false, isVegetarian: true },
  { name: 'Onion', calories: 40, protein: 1.1, fat: 0.1, fiber: 1.7, hasGluten: false, isVegetarian: true },
  { name: 'Garlic', calories: 149, protein: 6.4, fat: 0.5, fiber: 2.1, hasGluten: false, isVegetarian: true },
  { name: 'Sweet Potato', calories: 86, protein: 1.6, fat: 0.1, fiber: 3, hasGluten: false, isVegetarian: true },
  { name: 'White Potato', calories: 77, protein: 2, fat: 0.1, fiber: 2.2, hasGluten: false, isVegetarian: true },
  { name: 'Mushroom', calories: 22, protein: 3.1, fat: 0.3, fiber: 1, hasGluten: false, isVegetarian: true },
  { name: 'Zucchini', calories: 17, protein: 1.2, fat: 0.3, fiber: 1, hasGluten: false, isVegetarian: true },
  { name: 'Eggplant', calories: 25, protein: 1, fat: 0.2, fiber: 3, hasGluten: false, isVegetarian: true },
  { name: 'Green Beans', calories: 31, protein: 1.8, fat: 0.1, fiber: 2.7, hasGluten: false, isVegetarian: true },
  { name: 'Asparagus', calories: 20, protein: 2.2, fat: 0.1, fiber: 2.1, hasGluten: false, isVegetarian: true },
  { name: 'Cabbage', calories: 25, protein: 1.3, fat: 0.1, fiber: 2.5, hasGluten: false, isVegetarian: true },
  { name: 'Brussels Sprouts', calories: 43, protein: 3.4, fat: 0.3, fiber: 3.8, hasGluten: false, isVegetarian: true },
  { name: 'Corn Kernels', calories: 86, protein: 3.3, fat: 1.4, fiber: 2.7, hasGluten: false, isVegetarian: true },
  { name: 'Green Peas', calories: 81, protein: 5.4, fat: 0.4, fiber: 5.7, hasGluten: false, isVegetarian: true },
  { name: 'Chickpeas Cooked', calories: 164, protein: 8.9, fat: 2.6, fiber: 7.6, hasGluten: false, isVegetarian: true },
  { name: 'Lentils Cooked', calories: 116, protein: 9, fat: 0.4, fiber: 7.9, hasGluten: false, isVegetarian: true },
  { name: 'Black Beans Cooked', calories: 132, protein: 8.9, fat: 0.5, fiber: 8.7, hasGluten: false, isVegetarian: true },
  { name: 'Kidney Beans Cooked', calories: 127, protein: 8.7, fat: 0.5, fiber: 6.4, hasGluten: false, isVegetarian: true },
  { name: 'Tofu Firm', calories: 144, protein: 17.3, fat: 8.7, fiber: 2.3, hasGluten: false, isVegetarian: true },
  { name: 'Tempeh', calories: 193, protein: 20.3, fat: 10.8, fiber: 1.4, hasGluten: false, isVegetarian: true },
  { name: 'Edamame', calories: 121, protein: 11.9, fat: 5.2, fiber: 5.2, hasGluten: false, isVegetarian: true },
  { name: 'Hummus', calories: 166, protein: 7.9, fat: 9.6, fiber: 6, hasGluten: false, isVegetarian: true },
  { name: 'Almonds', calories: 579, protein: 21.2, fat: 49.9, fiber: 12.5, hasGluten: false, isVegetarian: true },
  { name: 'Walnuts', calories: 654, protein: 15.2, fat: 65.2, fiber: 6.7, hasGluten: false, isVegetarian: true },
  { name: 'Cashews', calories: 553, protein: 18.2, fat: 43.8, fiber: 3.3, hasGluten: false, isVegetarian: true },
  { name: 'Pistachios', calories: 562, protein: 20.2, fat: 45.3, fiber: 10.3, hasGluten: false, isVegetarian: true },
  { name: 'Peanuts', calories: 567, protein: 25.8, fat: 49.2, fiber: 8.5, hasGluten: false, isVegetarian: true },
  { name: 'Chia Seeds', calories: 486, protein: 16.5, fat: 30.7, fiber: 34.4, hasGluten: false, isVegetarian: true },
  { name: 'Flaxseeds', calories: 534, protein: 18.3, fat: 42.2, fiber: 27.3, hasGluten: false, isVegetarian: true },
  { name: 'Pumpkin Seeds', calories: 559, protein: 30.2, fat: 49, fiber: 6, hasGluten: false, isVegetarian: true },
  { name: 'Sunflower Seeds', calories: 584, protein: 20.8, fat: 51.5, fiber: 8.6, hasGluten: false, isVegetarian: true },
  { name: 'Sesame Seeds', calories: 573, protein: 17.7, fat: 49.7, fiber: 11.8, hasGluten: false, isVegetarian: true },
  { name: 'Rolled Oats', calories: 389, protein: 16.9, fat: 6.9, fiber: 10.6, hasGluten: false, isVegetarian: true },
  { name: 'Brown Rice Cooked', calories: 123, protein: 2.7, fat: 1, fiber: 1.8, hasGluten: false, isVegetarian: true },
  { name: 'White Rice Cooked', calories: 130, protein: 2.4, fat: 0.3, fiber: 0.4, hasGluten: false, isVegetarian: true },
  { name: 'Quinoa Cooked', calories: 120, protein: 4.4, fat: 1.9, fiber: 2.8, hasGluten: false, isVegetarian: true },
  { name: 'Pearl Barley Cooked', calories: 123, protein: 2.3, fat: 0.4, fiber: 3.8, hasGluten: true, isVegetarian: true },
  { name: 'Whole Wheat Bread', calories: 247, protein: 13, fat: 4.2, fiber: 6, hasGluten: true, isVegetarian: true },
  { name: 'Pasta Cooked', calories: 158, protein: 5.8, fat: 0.9, fiber: 1.8, hasGluten: true, isVegetarian: true },
  { name: 'Rye Bread', calories: 259, protein: 8.5, fat: 3.3, fiber: 5.8, hasGluten: true, isVegetarian: true },
  { name: 'Couscous Cooked', calories: 112, protein: 3.8, fat: 0.2, fiber: 1.4, hasGluten: true, isVegetarian: true },
  { name: 'Buckwheat Cooked', calories: 92, protein: 3.4, fat: 0.6, fiber: 2.7, hasGluten: false, isVegetarian: true },
  { name: 'Millet Cooked', calories: 119, protein: 3.5, fat: 1, fiber: 1.3, hasGluten: false, isVegetarian: true },
  { name: 'Greek Yogurt Plain', calories: 97, protein: 9, fat: 5, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Cottage Cheese', calories: 98, protein: 11.1, fat: 4.3, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Cheddar Cheese', calories: 403, protein: 24.9, fat: 33.1, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Mozzarella', calories: 280, protein: 28, fat: 17, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Milk 2 Percent', calories: 50, protein: 3.4, fat: 2, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Egg Whole', calories: 143, protein: 12.6, fat: 9.5, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Plain Kefir', calories: 64, protein: 3.5, fat: 3.5, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Chicken Breast', calories: 165, protein: 31, fat: 3.6, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Chicken Thigh', calories: 209, protein: 26, fat: 10.9, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Turkey Breast', calories: 135, protein: 29.1, fat: 1, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Lean Beef', calories: 217, protein: 26.1, fat: 11.8, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Ground Beef 80 Lean', calories: 254, protein: 17.2, fat: 20, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Pork Tenderloin', calories: 143, protein: 26, fat: 3.5, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Salmon', calories: 208, protein: 20, fat: 13, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Tuna', calories: 132, protein: 28, fat: 1.3, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Shrimp', calories: 99, protein: 24, fat: 0.3, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Cod', calories: 82, protein: 17.8, fat: 0.7, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Sardines', calories: 208, protein: 24.6, fat: 11.5, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Tilapia', calories: 96, protein: 20.1, fat: 1.7, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Duck Breast', calories: 337, protein: 19, fat: 28, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Lamb Loin', calories: 282, protein: 25.6, fat: 19.3, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Bacon', calories: 541, protein: 37, fat: 42, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Ham', calories: 145, protein: 21.4, fat: 5.5, fiber: 0, hasGluten: false, isVegetarian: false },
  { name: 'Olive Oil', calories: 884, protein: 0, fat: 100, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Coconut Oil', calories: 892, protein: 0, fat: 100, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Butter', calories: 717, protein: 0.9, fat: 81.1, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Soy Sauce', calories: 53, protein: 8.1, fat: 0.6, fiber: 0.8, hasGluten: true, isVegetarian: true },
  { name: 'Maple Syrup', calories: 260, protein: 0, fat: 0.1, fiber: 0, hasGluten: false, isVegetarian: true },
  { name: 'Honey', calories: 304, protein: 0.3, fat: 0, fiber: 0.2, hasGluten: false, isVegetarian: true },
  { name: 'Peanut Butter', calories: 588, protein: 25, fat: 50, fiber: 6, hasGluten: false, isVegetarian: true },
  { name: 'Dark Chocolate', calories: 598, protein: 7.8, fat: 42.6, fiber: 10.9, hasGluten: false, isVegetarian: true },
  { name: 'Basil', calories: 23, protein: 3.2, fat: 0.6, fiber: 1.6, hasGluten: false, isVegetarian: true },
  { name: 'Parsley', calories: 36, protein: 3, fat: 0.8, fiber: 3.3, hasGluten: false, isVegetarian: true },
  { name: 'Cilantro', calories: 23, protein: 2.1, fat: 0.5, fiber: 2.8, hasGluten: false, isVegetarian: true },
  { name: 'Ginger', calories: 80, protein: 1.8, fat: 0.8, fiber: 2, hasGluten: false, isVegetarian: true },
  { name: 'Turmeric Fresh', calories: 312, protein: 9.7, fat: 3.3, fiber: 22.7, hasGluten: false, isVegetarian: true },
  { name: 'Jalapeno', calories: 29, protein: 0.9, fat: 0.4, fiber: 2.8, hasGluten: false, isVegetarian: true },
  { name: 'Celery', calories: 14, protein: 0.7, fat: 0.2, fiber: 1.6, hasGluten: false, isVegetarian: true },
  { name: 'Beetroot', calories: 43, protein: 1.6, fat: 0.2, fiber: 2.8, hasGluten: false, isVegetarian: true },
];